[package]
name = "fedimint-plugin"
version = "0.1.0"
edition = "2021"


[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }
fedimint-build = "0.3.1"

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
